### ISSUE TITLE
[Proposal] Status command

### ISSUE THREAD

**Issue by marcus-herrmann** [marcus-herrmann/wireshell#8]
Combined output of PW version, admin-url, paths, admin theme name, wireshell version, paths, PHP executable, paths, database configuration, and so on.

tl;dr: Like `$ drush status`.

**Comment by marcus-herrmann** [comment]
-> 8ffe625e1dcdf45f0870eeeefd790a998403657c

**Comment by clsource** [comment]
Very Cool :+1: 

I suggest adding options like
--db --version and so on. So the user could choose what info needs.

Also I think it should be useful to add a simple counters like. 

Total number of templates
Total number of users
Total number of roles
Total number of fields

etc.
:smile:

**Comment by uiii** [comment]
I think the db password should not be visible by default in the output, maybe add some option to show it.

**Comment by clsource** [comment]
wireshell is for beign used in enviroments where you have full access to PW installation.
so nothing stops you from looking inside config.php and see the password.

In my opinion I see no problem showing the password as the default behaviour :smile:

**Comment by uiii** [comment]
I know, but I think it is the same as login form, the password is not visible by default for security resons. At least I din't expect the password will be in the output.

**Comment by clsource** [comment]
I see your point. maybe it should be added as an option. wireshell status --db --php
and the default behaviour only show general data like PW version.

**Comment by uiii** [comment]
Yes, it sounds good.

**Comment by clsource** [comment]
:+1:

**Comment by uiii** [comment]
Also, the readme seems to be outdated, there is only info about `show:version` command which does not exist.

**Comment by clsource** [comment]
Yes @marcus-herrmann  is working on a site will all the bells and whistles. So thats the reason the readme is not updated :+1:

**Comment by uiii** [comment]
:+1:
